-- 코드를 작성해주세요
SELECT T.ID, 
    CASE
        WHEN T.R >= 0.75 THEN 'CRITICAL'
        WHEN T.R >= 0.5 THEN 'HIGH'
        WHEN T.R >= 0.25 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS R
    FROM ECOLI_DATA
) T
ORDER BY T.ID;